config/routes.rb
RegisterTest2::Application.routes.draw do
  resources :unit_names

  resources :packages do 
    collection do
      put :recive
    end
  end

  resources :logcomponents

  resources :logunits

  resources :comp_todos do
    collection do
      put :task_done
      put :undo_task
    end
  end

  resources :unit_todos do
     collection do
      put :task_done
      put :undo_task
    end
  end
  resources :statuses

  resources :trackings

  resources :activity_logs

  resources :users

  resources :companies

  resources :brands

  resources :locations

  resources :todos do
    collection do
      put :update_individual
    end
  end
  resources :components do
    collection do 
      get :edit_individual
      put :update_individual
      post :import
    end
  end
  
  resources :sessions
  resources :units
  root :to => 'pages#index'

  resources :pages do
    collection do
      get :create_report
      get :get_unit_report
      get :get_unit_location
      get :get_component_report
      get :get_component_log_report
      get :get_unit_log_report
      get :get_todo_report
    end
  end
  get 'export', to: 'pages#export'
  get 'reminders', to: 'pages#reminders'
  get 'register', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/unit_name.rb
class UnitName < ActiveRecord::Base
  attr_accessible :title, :description
  has_many :units
end

app/controllers/unit_names_controller.rb
class UnitNamesController < ApplicationController
  before_action :set_unit_name, only: [:show, :edit, :update, :destroy]

  # GET /unit_names
  # GET /unit_names.json
  def index
    @unit_names = UnitName.all
  end

  # GET /unit_names/1
  # GET /unit_names/1.json
  def show
  end

  # GET /unit_names/new
  def new
    @unit_name = UnitName.new
  end

  # GET /unit_names/1/edit
  def edit
  end

  # POST /unit_names
  # POST /unit_names.json
  def create
    @unit_name = UnitName.new(unit_name_params)

    respond_to do |format|
      if @unit_name.save
        format.html { redirect_to @unit_name, notice: 'Unit name was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit_name }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_names/1
  # PATCH/PUT /unit_names/1.json
  def update
    respond_to do |format|
      if @unit_name.update(unit_name_params)
        format.html { redirect_to @unit_name, notice: 'Unit name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_names/1
  # DELETE /unit_names/1.json
  def destroy
    @unit_name.destroy
    respond_to do |format|
      format.html { redirect_to unit_names_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_name
      @unit_name = UnitName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_name_params
      params.require(:unit_name).permit(:title, :description)
    end
end

app/helpers/unit_names_helper.rb
module UnitNamesHelper
end

app/views/unit_names/_form.html.erb
<%= form_for @unit_name, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                unit_names_path, :class => 'btn' %>
  </div>
<% end %>

app/views/unit_names/edit.html.erb
<%- model_class = UnitName -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unit_names/index.html.erb
<%- model_class = UnitName -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @unit_names.each do |unit_name| %>
      <tr>
        <td><%= link_to unit_name.id, unit_name_path(unit_name) %></td>
        <td><%= unit_name.title %></td>
        <td><%= unit_name.description %></td>
        <td><%=l unit_name.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_name_path(unit_name), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_name_path(unit_name),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_name_path,
            :class => 'btn btn-primary' %>

app/views/unit_names/new.html.erb
<%- model_class = UnitName -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/unit_names/show.html.erb
<%- model_class = UnitName -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @unit_name.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @unit_name.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              unit_names_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_name_path(@unit_name), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_name_path(@unit_name),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>