config/routes.rb
RegisterTest2::Application.routes.draw do
  resources :unit_names

  resources :packages do 
    collection do
      put :recive
    end
  end

  resources :logcomponents

  resources :logunits

  resources :comp_todos do
    collection do
      put :task_done
      put :undo_task
    end
  end

  resources :unit_todos do
     collection do
      put :task_done
      put :undo_task
    end
  end
  resources :statuses

  resources :trackings

  resources :activity_logs

  resources :users

  resources :companies

  resources :brands

  resources :locations

  resources :todos do
    collection do
      put :update_individual
    end
  end
  resources :components do
    collection do 
      get :edit_individual
      put :update_individual
      post :import
    end
  end
  
  resources :sessions
  resources :units
  root :to => 'pages#index'

  resources :pages do
    collection do
      get :create_report
      get :get_unit_report
      get :get_unit_location
      get :get_component_report
      get :get_component_log_report
      get :get_unit_log_report
      get :get_todo_report
    end
  end
  get 'export', to: 'pages#export'
  get 'reminders', to: 'pages#reminders'
  get 'register', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/comp_todo.rb
class CompTodo < ActiveRecord::Base
  has_one :todo
  belongs_to :component
  before_save :new_todo
  before_destroy :destroy_todo
  
  attr_accessible :todo_id, :component_id, :level, :task,:title
  validates :component_id, presence: true
  validates :level, presence: true
  validates :task, presence: true
  validates :title, presence: true
  
  
  
  private 
  
  def new_todo
    todo = Todo.new
    todo.done = false
    todo.save!
    self.todo_id = todo.id
    
  end

  def destroy_todo
    Todo.find(self.todo_id).destroy!
  end
end

app/controllers/comp_todos_controller.rb
class CompTodosController < ApplicationController
  before_action :set_comp_todo, only: [:show, :edit, :update, :destroy]
  helper_method :get_comp_todo
  # GET /comp_todos
  # GET /comp_todos.json
  def index
    @comp_todos = CompTodo.all
  end

  # GET /comp_todos/1
  # GET /comp_todos/1.json
  def show
  end

  # GET /comp_todos/new
  def new
    @comp_todo = CompTodo.new
    @comp_id = params[:comp_id].to_i
  end

  # GET /comp_todos/1/edit
  def edit
  end
  def task_done
    get_comp_todo
    @todo.update({done: true})
    #Todo.update_all({done: true}, {id: params[:todo_ids]})
    redirect_to component_path(@comp_todo.component_id), notice: 'Task is done'
  end
  
  def undo_task
    get_comp_todo
    @todo.update({done: false})
    redirect_to component_path(@comp_todo.component_id), notice: 'Task is un-done'
  end
  # POST /comp_todos
  # POST /comp_todos.json
  def create
    @comp_todo = CompTodo.new(comp_todo_params)

    respond_to do |format|
      if @comp_todo.save
        format.html { redirect_to component_path(@comp_todo.component_id), notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comp_todo }
      else
        format.html { redirect_to component_path(@comp_todo.component_id), alert: 'Task was not created please fill inn all the fields when making a task.' }
        format.json { render json: @comp_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comp_todos/1
  # PATCH/PUT /comp_todos/1.json
  def update
    respond_to do |format|
      if @comp_todo.update(comp_todo_params)
        format.html { redirect_to @comp_todo, notice: 'Task was updated' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comp_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comp_todos/1
  # DELETE /comp_todos/1.json
  def destroy
    @comp_todo.destroy
    respond_to do |format|
      format.html { redirect_to component_path(@comp_todo.component), notice: "Task was deleted" }
      format.json { head :no_content }
    end
  end

  private
  def get_comp_todo
    @todo = Todo.find(params[:todo_id])
    @comp_todo = CompTodo.where("todo_id = ?", @todo.id).first
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comp_todo
      @comp_todo = CompTodo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_todo_params
      params.require(:comp_todo).permit(:todo_id, :level, :task, :component_id, :title)
    end
end

app/helpers/comp_todos_helper.rb
module CompTodosHelper
end

app/views/comp_todos/_form.html.erb
<%= form_for @comp_todo, :html => { :class => 'form-horizontal' } do |f| %>
   <% if @comp_todo.errors.any? %>
    <div class="error_messages">
      <h4><%= pluralize(@comp_todo.errors.count, "error") %> prohibited this task from being saved:</h4>
      <ul>
      <% @comp_todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  	<div class="control-group">
   	 <%= f.label :level, :class => 'control-label' %>
    	<div class="controls">
   	 		<%= f.select :level, options_for_select([["Low", "low"], ["Medium", "medium"],["High", "high"]]) %>
		</div>
	</div>
  <div class="control-group">
    <%= f.label :task, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :task, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comp_todos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comp_todos/edit.html.erb
<%- model_class = CompTodo -%>
<div class="page-header">
  <h1>Edit task</h1>
</div>
<%= render :partial => 'form' %>

app/views/comp_todos/index.html.erb
<%- model_class = CompTodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:todo_id) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:task) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comp_todos.each do |comp_todo| %>
      <tr>
        <td><%= link_to comp_todo.id, comp_todo_path(comp_todo) %></td>
        <td><%= comp_todo.todo_id %></td>
        <td><%= comp_todo.level %></td>
        <td><%= comp_todo.task %></td>
        <td><%=l comp_todo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comp_todo_path(comp_todo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comp_todo_path(comp_todo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comp_todos/new.html.erb
<%- model_class = CompTodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comp_todos/show.html.erb
<%- model_class = CompTodo -%>
<div class="page-header">
<h2><%= @comp_todo.title %></h2>
</div>

<dl class="dl-horizontal">
   <dt><strong>Component:</strong></dt>
  <dd><%= Brand.find(@comp_todo.component.brand_id).name %> | <%= @comp_todo.component.comp_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @comp_todo.level.capitalize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:task) %>:</strong></dt>
  <dd><%= @comp_todo.task %></dd>
   
</dl>

<div class="form-actions">
<% if ! Todo.find(@comp_todo.todo_id).done %>
	<%= form_tag task_done_comp_todos_path, method: :put do %>
		<%= hidden_field_tag "todo_id", @comp_todo.todo_id %>
		<%=submit_tag "Done task", :class => "btn btn-success" %>
	<% end %>
<% else %>
	<%= form_tag undo_task_comp_todos_path, method: :put do %>
		<%= hidden_field_tag "todo_id", @comp_todo.todo_id %>
		<%=submit_tag "Undo task", :class => "btn btn-primary" %>
	<% end %>

<% end %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              component_path(@comp_todo.component), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comp_todo_path(@comp_todo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comp_todo_path(@comp_todo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>