config/routes.rb
RegisterTest2::Application.routes.draw do
  resources :unit_names

  resources :packages do 
    collection do
      put :recive
    end
  end

  resources :logcomponents

  resources :logunits

  resources :comp_todos do
    collection do
      put :task_done
      put :undo_task
    end
  end

  resources :unit_todos do
     collection do
      put :task_done
      put :undo_task
    end
  end
  resources :statuses

  resources :trackings

  resources :activity_logs

  resources :users

  resources :companies

  resources :brands

  resources :locations

  resources :todos do
    collection do
      put :update_individual
    end
  end
  resources :components do
    collection do 
      get :edit_individual
      put :update_individual
      post :import
    end
  end
  
  resources :sessions
  resources :units
  root :to => 'pages#index'

  resources :pages do
    collection do
      get :create_report
      get :get_unit_report
      get :get_unit_location
      get :get_component_report
      get :get_component_log_report
      get :get_unit_log_report
      get :get_todo_report
    end
  end
  get 'export', to: 'pages#export'
  get 'reminders', to: 'pages#reminders'
  get 'register', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :unit_todo
  belongs_to :comp_todo
  
  attr_accessible  :done
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
  
   #@unit_todos = UnitTodo.all
   #@unit_todos = @unit_todo.where("unit_id == ?", params[:unit_id]) if  ! params[:unit_id].blank?
   
   @unit = nil
   @comp = nil

    if(params[:unit_id] != nil && params[:unit_id] != "" && Unit.exists?(params[:unit_id]))
      @unit_id = params[:unit_id]

      @unit = Unit.find(params[:unit_id])
      @unit_todos = @unit.unit_todos
      @comps = @unit.components
      
      @comp_todos =  CompTodo.where(component_id: @comps)

    elsif (params[:comp_id] != nil && params[:comp_id] != "" && Component.exists?(params[:comp_id]))
      @comp = Component.find(params[:comp_id])
      @comp_todos = @comp.comp_todos
      @unit_todos = Array.new
            
    else    
   
      @unit_todos = UnitTodo.all
      @comp_todos = CompTodo.all
      
    end 
  end
  def update_individual
     Todo.update_all({done: true}, {id: params[:todo_ids]})
     redirect_to todos_path, notice: "Tasks done"
    
  end
  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    unit_id = 
    respond_to do |format|
      if @todo.update(todo_params)
       
        format.html { redirect_to todos_url , notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:done, :todo_ids)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_for @todo, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :done, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :done, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                todos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">

<% if @unit != nil %>
<h3>Task on unit <%= @unit.unit_id %> <small>and components assigned to this unit</small></h3>
<% elsif @comp != nil  %>
<h3>Tasks on component <%= @comp.brand.name %> | <%= @comp.comp_id %></h3>
<% else %>
<h3>Full list</h3>
<% end %>
</div>
<div class="control-group">
<script>
	function getByUnitOrComp()
	{
		var unit = document.getElementById("todo-unit-id");
		var unit_id = unit.options[unit.selectedIndex].value;
		var comp = document.getElementById("todo-comp-id");
		var comp_id = comp.options[comp.selectedIndex].value;
		window.location.replace("/todos?unit_id=" + unit_id + "&comp_id=" + comp_id  )
	}
</script>
    <div class="controls">
    	<select id="todo-unit-id" style="margin:0px 0 0 0">
    		<option value="">Search by unit:</option>
    		<% Unit.all.each do |u| %>
    		
    		<option value="<%= u.id %>">
    			<%= u.unit_id %>
    		</option>
    		<% end %>
    	</select>
    		<select id="todo-comp-id" style="margin:0px 0 0 0">
    		<option value="">Search by component:</option>
    		<% Component.all.each do |c| %>
    		<option value="<%= c.id %>">
    			<%= c.comp_id %>
    		</option>
    		<% end %>
    	</select>
    	<a href="#" class="btn btn-primary" onclick="getByUnitOrComp()">Search</a>
      	<%= link_to "Show all", todos_path, :class => 'btn btn-primary' %>
    </div>
  </div>

<h4> Incompleted tasks</h4>
<%= form_tag update_individual_todos_path, method: :put do %>
<table class="table table-striped" id="incompleted-tasks">
  <thead>
    <tr>
     
      <th></th>
      <th>Unit or Component</th>
      <th>Title</th>
      <th>Date</th>
      <th>Task</th>
      
      
      </tr>
    </thead>
<tbody>


 
  <% @unit_todos.each do |u|%>
	<% todo = Todo.find(u.todo_id) %>
	<% if ! todo.done %>
<tr>  
	<td><%= check_box_tag "todo_ids[]", todo.id %></td>	
	<td><%= link_to "Unit " + u.unit.unit_id.to_s, u.unit %></td>
  	<td><%= link_to u.title, unit_todo_path(u)%> </td>
  	<td><%= u.created_at.strftime("%d %B %Y") %></td>
  	<td><%= u.task %></td>
</tr>
  <% end %>
<% end %>
 <% @comp_todos.each do |u|%>
	<% todo = Todo.find(u.todo_id) %>
	<% if ! todo.done %>
	
  <tr>  
	  <td><%= check_box_tag "todo_ids[]", todo.id %></td>
	  <td><%= link_to u.component.brand.name + " " + u.component.comp_id.to_s, u.component%></td>
	 <td> <%= link_to u.title, comp_todo_path(u)%></td>
	 <td><%= u.created_at.strftime("%d %B %Y") %></td>
  	<td><%= u.task %></td>
 </tr>
  
  <% end %>
<% end %>
</tbody>
</table>
<div class="form-actions">
  <%= submit_tag "Done checked", :class => "btn btn-success" %>
</div>
<% end %>

<h4>Comlpete Tasks</h4>
<table class="table table-striped" id="completed-tasks">
  <thead>
      <tr>
	      <th>Title</th>
	      <th>Date</th>
	      <th>Task</th>
      </tr>
    </thead>
<tbody>

   <% @unit_todos.each do |u|%>
	<% todo = Todo.find(u.todo_id) %>
	<% if todo.done %>
	<tr>
	
  <td> <%= link_to u.title, unit_todo_path(u)%></td>
 <td><%= u.created_at.strftime("%d %B %Y") %></td>
  	<td><%= u.task %></td>
  	</tr>
  	
  <% end %>
<% end %>
   <% @comp_todos.each do |u|%>
	<% todo = Todo.find(u.todo_id)%>
	<% if todo.done %>
	
  	<tr>
	  	<td> <%= link_to u.title, comp_todo_path(u)%></td>
	 	<td><%= u.created_at.strftime("%d %B %Y") %></td>
  		<td><%= u.task %></td>
  	</tr>

  
  	</div>
  	<% end %>
  <% end %>
</tbody>
</table>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @todo.done %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              todos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_path(@todo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_path(@todo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>