config/routes.rb
RegisterTest2::Application.routes.draw do
  resources :unit_names

  resources :packages do 
    collection do
      put :recive
    end
  end

  resources :logcomponents

  resources :logunits

  resources :comp_todos do
    collection do
      put :task_done
      put :undo_task
    end
  end

  resources :unit_todos do
     collection do
      put :task_done
      put :undo_task
    end
  end
  resources :statuses

  resources :trackings

  resources :activity_logs

  resources :users

  resources :companies

  resources :brands

  resources :locations

  resources :todos do
    collection do
      put :update_individual
    end
  end
  resources :components do
    collection do 
      get :edit_individual
      put :update_individual
      post :import
    end
  end
  
  resources :sessions
  resources :units
  root :to => 'pages#index'

  resources :pages do
    collection do
      get :create_report
      get :get_unit_report
      get :get_unit_location
      get :get_component_report
      get :get_component_log_report
      get :get_unit_log_report
      get :get_todo_report
    end
  end
  get 'export', to: 'pages#export'
  get 'reminders', to: 'pages#reminders'
  get 'register', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/unit.rb
class Unit < ActiveRecord::Base

  belongs_to :company
  belongs_to :unit_name
  has_many :components
  has_many :unit_todos
  has_many :logunits
  
  attr_accessible :available, :comment, :last_check, :location, :unit_id, :unit_name_id, :company_id, :tracking_id, :client_id
  validates :unit_id, presence: true
  validates :last_check, presence: true
  validates :unit_id, :uniqueness => {:scope => :unit_id, message: "id allready taken. Must be unique."}
  validate :company_exists
   
  after_create :logunit
  before_create :set_available


def logunit
  log = Logunit.new
  log.unit_id = self.id
  log.client_id = self.company_id
  log.send_date = DateTime.now
  log.sent_from = RegisterTest2::Application::LOCATION_SCANWELL_NO
  log.sent_to = RegisterTest2::Application::LOCATION_SCANWELL_NO
  log.status = Status.find(Location.find(RegisterTest2::Application::LOCATION_SCANWELL_NO).status).id
  log.arrive_date = DateTime.now
  log.save
end

def set_available
  self.available = true
end
private 

def company_exists
    if company_id.blank?
      errors.add(:base, "You must choose an owner") 
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction, :setup_new_registration_for_tracking, :get_by_status_id, :check_comp_calibration
  # GET /units
  # GET /units.json
  def index
   #get_by_status_id
    @unitnames = UnitName.count
    @units = Unit.all
    
    #lms = UnitName.where("title == ? ", "LMS")
    #@lms = Unit.where("unit_name_id == ?", lms)
    
    respond_to do |format|
    format.html
    format.csv { send_data @units.to_csv }
    format.xls 
  end
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    if Company.all.empty?
      redirect_to new_company_path, alert: "You need to create a company before creating a unit."
    end
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    
    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
      
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.components.each do |c|
      c.update_attributes(:available => true)
    end   
    @unit.destroy
    
    
    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was deleted." }
      format.json { head :no_content }
    end
  end

  private
  
   def check_comp_calibration(unit)
   alert = 0
   
   unit.components.each do |c|
     if (c.last_check + 1.year) <= DateTime.now + 30.days
       alert = alert + 1
       
     end
     
   end
   return alert
   
 end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
      @old_unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:unit_id, :unit_name_id, :location, :last_check, :available, :comment,:company_id, :tracking_id, :client_id)
    end
      
  def sort_column
    Unit.column_names.include?(params[:sort]) ? params[:sort] : "last_check"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
  
  def get_by_status_id 
     if(params[:owner] != "" && params[:owner] != nil && Company.exists?(params[:owner]))
       @owner = Company.find(params[:owner])
       @owner_id = @owner.id
       units = Unit.where("company_id = ?", params[:owner]).order("last_check asc")
     else
     
     units = Unit.order("last_check asc")
     end
     @units = Array.new
     
    if (params[:status_id] != "" && params[:status_id] != nil && Status.exists?(params[:status_id]))
          
      @status = params[:status_id]
      @status_name = Status.find(params[:status_id]).name
      #units = Unit.all
      #@units = Array.new
      units.each do |u|
       if u.logunits.last.status == @status.to_i
         @units << u
        end
      end
      
    else 
      @units = units
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
 

  
  def get_total_todos(unit)
    total = 0
    unit_todos = unit.unit_todos
    
    unit_todos.each do |u|
      if ! Todo.find(u.todo_id).done
        total += 1
      end
    end
    components = unit.components
    
    components.each do |c|
      c.comp_todos.each do |ct|
        if ! Todo.find(ct.todo_id).done
          total += 1
        end
      end
    end
    return total
  end
  
  def get_total(unit)
    return get_todos_for_components_on_unit(unit).count + get_todos_for_unit(unit).count
  end
  def get_todos_for_components_on_unit(unit)
    components = unit.components
    comp_todo = Array.new
    
    components.each do |c|
      c.comp_todos.each do |ct|
        if ! Todo.find(ct.todo_id).done
         comp_todo << ct
        end
      end
  end 
      return comp_todo
  end
  
  def get_todos_for_unit(unit)
    unit_todos = unit.unit_todos
    unit_todos_un_done = Array.new
    
    unit_todos.each do |u|
      if ! Todo.find(u.todo_id).done
       unit_todos_un_done << u
      end
    end
    return unit_todos_un_done
  end


end

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
 		<% if @unit.errors.any? %>
		    <div class="alert">
		      <h4><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h4>
		      <ul>
		      <% @unit.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
  		<% end %>
    <div class="control-group">
    <%= f.label 'Type', :class => 'control-label' %>
    <div class="controls">
     <%= f.collection_select :unit_name_id, UnitName.all, :id, :title, :include_blank => "Select a type" %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :unit_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unit_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Owner', :class => 'control-label' %>
    <div class="controls">
     <%= f.collection_select :company_id, Company.all, :id, :name, :include_blank => "Select a owner" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_check, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_check, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :available, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :available, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comment, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                units_path, :class => 'btn' %>
  </div>
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/index.html.erb
<%- model_class = Unit -%>

<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> 
  	
  	<% status_param = ""%>
  	<% if @status != nil %>
  	<% status_param = @status %>
  	<%= Status.find(@status).name %>
  	<% end %>
  	<% owner_param = "" %>
  	<% if @owner != nil %>
  	owned by
  	<% owner_param = @owner.id %>
  	<%= @owner.name %>
  	<% end %></h3>
  
  	
</div>
<div class="control-group">
<script>
	function getStatus()
	{
		var status = document.getElementById("status_value");
		var owner = document.getElementById("owner");
		var owner_value = owner.options[owner.selectedIndex].value;
		var status_value = status.options[status.selectedIndex].value;
		console.log(status_value);
		console.log(owner_value)
		
		window.location.replace("/units?status_id=" + status_value + "&owner=" + owner_value)
	}
</script>
    <div class="controls">
    	<select id="status_value" style="margin:0px 0 0 0">
    		<option value="">Search by status:</option>
    		<% Status.all.each do |s| %>
    		<option value="<%= s.id %>">
    			<%= s.name %>
    		</option>
    		<% end %>
    	</select>
    		<select id="owner" style="margin:0px 0 0 0">
    		<option value="">Search by owner:</option>
    		<% Company.all.each do |c| %>
    		<option value="<%= c.id %>">
    			<%= c.name %>
    		</option>
    		<% end %>
    	</select>
    	<a href="#" class="btn btn-primary" onclick="getStatus()">Search</a>
      	<%= link_to "Show all", units_path, :class => 'btn btn-primary' %>
    </div>
  </div>

  	
<table class="table table-striped" id="units">
	
  <thead>
    <tr>
     
      <th>Unit id</th>
      <th>Owner</th>
      <th>Status</th>
      <th>Location</th>
      <th>Next check</th>
      <th>Alerts</th>
    
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        
        <td><%= link_to unit.unit_id, unit %></td>
         <% if unit.company_id != nil %>
       <% company = Company.find(unit.company_id) %>
        <td><%= link_to company.name, company  %></td>
        <% else %>
        <td>No owner</td>
        <% end %>
        
        <td><%= Status.find(unit.logunits.last.status).name if Status.exists?(unit.logunits.last.status) %></td>
        <td><%= Location.find(unit.logunits.last.sent_to).name if Location.exists?(unit.logunits.last.sent_to)  %></td> 
        
       
        <td><%= unit.last_check + 1.year %>
        	<% days = (unit.last_check + 1.year)- DateTime.now %>
        	<% if days > 90 %>
        	<span style="color:#00ff00;">
        	<% elsif days < 90 && days > 30 %>
        	<span style="color:#FF9900;">
        	<% else %>
        	<span style="color:#bb0000;">
        	<% end %>
        	(<%= days.to_i%> days)
        	</span>
        	
        </td>
        
        <td><%= check_comp_calibration(unit) %></td>
       
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/units/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      	 <Cell><Data ss:Type="Date"><%= DateTime.now.to_formatted_s(:long) %></Data></Cell>
      </Row>
     <% lines = 3 %>
     
     <% while lines > 0 do %>
     	<Row>
     	</Row>
     	<% lines =  lines - 1%>
     <% end %>
      <Row>
        <Cell><Data ss:Type="String">Unit id</Data></Cell>
        <Cell><Data ss:Type="String">Owner</Data></Cell>
        <Cell><Data ss:Type="String">Last check</Data></Cell>
        <Cell><Data ss:Type="String">Next check</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>
    <% @units.each do |unit| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= unit.unit_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= Company.find(unit.company_id).name %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= unit.last_check %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= unit.last_check + 1.year %></Data></Cell>
        <Cell><Data ss:Type="String"><%= Location.find(unit.location).name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= Status.find(Tracking.find(unit.tracking_id).status_id).name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1>
  	<%= @unit.unit_id %>
    
    <small> 
    <% if @unit.logunits.count > 0 %>
    	<%= Status.find(@unit.logunits.last.status).name if Status.exists?(@unit.logunits.last.status)%>
    	@ <% loc = Location.find(@unit.logunits.last.sent_to) %> 
    	<%= loc.name %> (<%= loc.company.name %>)
    <% end %>
    
	
	</small>
  </h1>

 <%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

  <% total = get_total(@unit)%>
 <!--
<%= link_to todos_path(:unit_id => @unit.id), :class => "btn btn-primary" do %>
  To do
  <span class="badge <% if total > 0 %>badge-red <% end %>"><%= total %></span>
<% end %>
-->

<div class="form-actions">
	<% if is_in_transit_unit(@unit) %>
		<%= link_to "Go to package", @unit.logunits.last.package, :class => 'btn btn-primary' %>
	<% end %>
	<%= link_to "History log", logunits_path(:unit_id => @unit.id), :class => 'btn btn-primary' %>
	<a data-toggle="modal" href="#add-task" class="btn btn-primary">Add a task</a>
<div class="btn-group">
 <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    To do <span class="badge <% if total > 0 %>badge-red <% end %>"><%= total %></span>
  </button>
  <ul class="dropdown-menu grey" role="menu" >

  	 <% get_todos_for_unit(@unit).each do |c|%>
     <li><%= link_to c do %>
    	<%= c.title %>
    	<% if c.level == "high" %>
    	<% color = "badge-red" %>
    	<% elsif c.level == "medium"%>
    	<% color = "badge-orange" %>
    	<% elsif c.level == "low"%>
    	<% color = "badge-green" %>
    	<% end %>
    	<span class="badge <%= color %>"> </span>
    	<% end %>
	</li>
     <li class="divider"></li>
    
    <% end %>
    <% get_todos_for_components_on_unit(@unit).each do |c|%>
    <li><%= link_to c do %>
    	<%= c.title %>
    	<% if c.level == "high" %>
    	<% color = "badge-red" %>
    	<% elsif c.level == "medium"%>
    	<% color = "badge-orange" %>
    	<% elsif c.level == "low"%>
    	<% color = "badge-green" %>
    	<% end %>
    	<span class="badge <%= color %>"> </span>
    	<% end %>
	</li>
     <li class="divider"></li>
    
    <% end %>

   <li><%= link_to 'Show all...', todos_path(:unit_id => @unit.id)%></li>

    </ul>
 </div> 
 <% days = (@unit.last_check + 1.year)- DateTime.now %>
 <h4 style="float:right"><%= days.to_i %> days</h4>
</div>
  
 <!-- Modal -->
  <div class="modal fade" id="check-unit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Check in unit</h4>
        </div>
        <div class="modal-body">
			<% @logunit_edit = @unit.logunits.last %>
			<%= form_for @logunit_edit, :html => { :class => 'form-horizontal', :role => "form" } do |f| %>
			<div class="control-group">
		    <%= f.label :status, :class => 'control-label' %>
		    <div class="controls">
		      <%= f.collection_select :status, Status.all, :id, :name, :include_blank => "Select a status" %>
		    </div>
		  </div>
		<%= f.hidden_field :arrive_date, :value => DateTime.now %>
		<%= f.hidden_field :recived_by, :value => current_user.id %>
			
        </div>
        <div class="modal-footer">
          <%= f.submit "Check in", :class => 'btn btn-primary' %>
		  <% end %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <!-- Modal -->
  <div class="modal fade" id="add-task" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add a task</h4>
        </div>
        <div class="modal-body">
			<% @unit_todo = UnitTodo.new %>
			<%= form_for @unit_todo, :html => { :class => 'form-horizontal', :role => "form" } do |f| %>
			<div class="control-group">
				
			    <%= f.label :title, :class => 'control-label' %>
			    <div class="controls">
			      <%= f.text_field :title, :class => 'text_field' %>
			      <%= f.hidden_field :unit_id, :value => @unit.id %>
			      </div>
			</div>
			<div class="control-group">
				
			    <%= f.label :level, :class => 'control-label' %>
			    <div class="controls">
			    <%= f.select :level, options_for_select([["Low", "low"], ["Medium", "medium"],["High", "high"]]) %>
			</div>
			</div>
			<div class="control-group">
				 <%= f.label :task, :class => 'control-label' %>
			<div class="controls">
			      <%= f.text_area :task, :class => 'text_field' %>
			</div>
			</div>
			

        </div>
        <div class="modal-footer">
          <%= f.submit "Create task", :class => 'btn btn-primary' %>
		  <% end %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
<dl class="dl-horizontal">
	<% if @unit.company_id != nil %>
 <dt><strong>Owner:</strong></dt>
  <dd><%= Company.find(@unit.company_id).name %></dd>
 <% end %>
  <dt><strong>Leased by:</strong></dt>
  <dd><%= @unit.logunits.last.client_id != nil ? Company.find(@unit.logunits.last.client_id).name : "none"   %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_check) %>:</strong></dt>
  <dd><%= @unit.last_check %></dd>
  <dt><strong><%= model_class.human_attribute_name(:available) %>:</strong></dt>
  <dd><% if @unit.available %>
  	Yes
  	<% else %>
  	No
  	<% end %>
  </dd>
  
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @unit.comment %></dd>

</dl>
<h5>Components on this unit</h5>
	<%= form_tag edit_individual_components_path, method: :get do %>
<table class="table table-striped" id="unit-comps">
  <thead>
    <tr>
      	<th></th>
      	<th>Serial number</th>
	    <th>Type</th>
	    <th>Next check</th>
	   
	   
    
    
    </tr>
  </thead>
  <tbody>
  
    <% @unit.components.order("brand_id desc").each do |c|%>
    
      <tr>
        <td><%= check_box_tag "component_ids[]", c.id%></td>
        <td><%= link_to c.comp_id, c %></td>
         <td><%= Brand.find(c.brand_id).name %></td>
         <% d = (c.last_check + 1.year)- DateTime.now%>
        <td><%= c.last_check + 1.year %>
        <% if d > 90 %>
        	<span style="color:#00ff00;">
        	<% elsif d < 90 && d > 30 %>
        	<span style="color:#FF9900;">
        	<% else %>
        	<span style="color:#bb0000;">
        	<% end %>
        	(<%= d.to_i %> days)
        	</span>
        	
        </td>
        
       
        </tr>
        
      
	   <% end %>
        </tbody>
        </table>
<div class="form-actions">
	<%= submit_tag "Edit Checked", :class => "btn" %>
	  <% end %>
</div>